### ISSUE TITLE
Light Theme for SoftUni Judge

### ISSUE THREAD

**Issue by Ivelina8** [SoftUni-Internal/OpenJudgeSystem#1356]
### Expected Behavior: We are ready with the Light Theme of SoftUni Judge. You can see the design here - https://www.figma.com/design/o1ASbkZBDOEQTzUxMNRB4z/judge?node-id=1632-690&node-type=FRAME&t=RLQA8wJdL7CwxeVc-0

<img width="782" alt="image" src="https://github.com/user-attachments/assets/c0c29cde-47b3-40cf-988b-b49b9e1a1eb2">

### Platform: 
SoftUni Judge (https://judge.softuni.bg)

**Comment by gogo4ds** [comment]
Moved to another repo
